### ISSUE TITLE
Major changes in CFs from 1.0 to 1.1

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/bw_recipe_2016#2]
From @romainsacchi: "In the Simapro implementation _(i.e. 1.0)_, Cr(VI) has a CF of 60 and 89 kg 1,4-DCB-eq, for emissions to "air, unspec." and "urban air", respectively, while we have a CF of 142,000 and 205,000 for "urban air " and "rural air", as listed in the Recipe Excel file. It's safe to say that it is a significant difference.

**Comment by romainsacchi** [comment]
Is this really an issue? If we want to reproduce Simapro's results, it is an issue. But if we want to have an up-to-date implementation, it maybe is not.

**Comment by cmutel** [comment]
50f36000d23f1ce3b99b8770b31631ba9e9c21ad allows import of 1.0 and _two_ versions of 1.1; closing this as an issue, but we should definitely follow up and do a systematic analysis of the differences, and then communicate with ReCiPe team.
