### ISSUE TITLE
ReCiPe2016 versions

### ISSUE THREAD

**Issue by hewigger** [brightway-lca/bw_recipe_2016#6]
Hi there,
I was looking for the most recent ReCiPe2016 version. As I use the latest activity-browser (dev version), I was wondering which ReCiPe2016 is latest? This one here with V1.1 or in the BW2 with 1.13?

Best,
Henning

**Comment by romainsacchi** [comment]
Hi @hewigger ,

the v.1.13 that comes with BW2 is in fact an update of ReCiPe 2008 (from 2013 if I recall correctly).

This here is rather an attempt at implementing ReCiPe 2016. And I say "an attempt" as it has not proved totally successful yet.
We're still having difficulties with toxicity-related indicators and are not really receiving the needed support from the team behind ReCiPe. In other words, I would not use it just yet. Your best hope at getting ReCiPe 2016 is maybe by waiting for the next major ecoinvent update.

**Comment by hewigger** [comment]
Hi @romainsacchi,
thanks a lot for the answer for clarifying the different versions.

**Comment by Lamagentle** [comment]
Hello, since it's 2025 now, and the version of ReCiPe2016 is 1.03 in my activity-browser.. I wonder if there is a method that could update it? Thanks guys!
